CREATE DATABASE SQLTASK2

USE SQLTASK2
CREATE TABLE EMPLOYEES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(30) NOT NULL,
SURNAME NVARCHAR(30) NOT NULL,
SALARY MONEY CHECK(SALARY>=250),
EMAIL NVARCHAR(50) UNIQUE
)


INSERT INTO EMPLOYEES VALUES
('IBRAHIM1','QASIMZADA',2500,'MAIL1@GMAIL.COM'),
('IBRAHIM2','QASIMZADA',500,'MAIL2@GMAIL.COM'),
('IBRAHIM3','QASIMZADA',1500,'MAIL3@GMAIL.COM'),
('IBRAHIM4','QASIMZADA',750,'MAIL4@GMAIL.COM'),
('IBRAHIM5','QASIMZADA',5500,'MAIL5@GMAIL.COM'),
('IBRAHIM6','QASIMZADA',4500,'MAIL6@GMAIL.COM')

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 250 AND 500



SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)FROM EMPLOYEES)


UPDATE EMPLOYEES
SET SALARY = (SELECT AVG(SALARY)FROM EMPLOYEES)
WHERE SALARY < (SELECT AVG(SALARY)FROM EMPLOYEES)

SELECT ID,CONCAT(NAME,' ',SURNAME) AS FULLNAME,SALARY,EMAIL FROM EMPLOYEES
WHERE LEN(CONCAT(NAME,' ',SURNAME))>10

SELECT * FROM EMPLOYEES
WHERE EMAIL LIKE '%@GMAIL.COM'


SELECT CONCAT(NAME,' ',SURNAME) AS FULLNAME,SUBSTRING(EMAIL, CHARINDEX('@', EMAIL) + 1, LEN(EMAIL)) 
AS DOMAIN 
FROM EMPLOYEES;


SELECT COUNT(*) * 100 / (SELECT COUNT(*) FROM EMPLOYEES) FROM EMPLOYEES
WHERE Salary > (SELECT AVG(Salary) FROM EMPLOYEES);


